// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8KLt6JfqICIi6bRtBtyv-BeeN3SFvxiI',
    appId: '1:821826092003:web:fcbba49a6f14527ca4fed6',
    messagingSenderId: '821826092003',
    projectId: 'app-test-cloudwalk',
    authDomain: 'app-test-cloudwalk.firebaseapp.com',
    storageBucket: 'app-test-cloudwalk.appspot.com',
    measurementId: 'G-W5N97Q3B70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDzv8kkVd8jCMqwkIgSV2GyhfXIlb64Ww',
    appId: '1:821826092003:android:b6a1a7f89abc16dda4fed6',
    messagingSenderId: '821826092003',
    projectId: 'app-test-cloudwalk',
    storageBucket: 'app-test-cloudwalk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjvxNOocroIzT9ACvfD2LPA1zAFWLm9vY',
    appId: '1:821826092003:ios:2d38216c643cddd4a4fed6',
    messagingSenderId: '821826092003',
    projectId: 'app-test-cloudwalk',
    storageBucket: 'app-test-cloudwalk.appspot.com',
    iosBundleId: 'br.dev.yago.appTestCloudwalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjvxNOocroIzT9ACvfD2LPA1zAFWLm9vY',
    appId: '1:821826092003:ios:9e60e006bc0bccaaa4fed6',
    messagingSenderId: '821826092003',
    projectId: 'app-test-cloudwalk',
    storageBucket: 'app-test-cloudwalk.appspot.com',
    iosBundleId: 'br.dev.yago.appTestCloudwalk.RunnerTests',
  );
}
